moduleImport:
  delay:
    initial:
      seconds: 0
spring:
  datasource:
    password: company-profile-service
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: company-profile-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false
  h2:
    console:
      enabled: true
