{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prox-company-profile-service.fullname" . }}
  labels:
    {{- include "prox-company-profile-service.labels" . | nindent 4 }}
data:
  application.yml: |-
    keycloak:
      auth-server-url: https://login.aws.innovation-hub.de/auth
      bearer-only: true
      cors: false
      principal-attribute: preferred_username
      realm: archilab
      resource: prox-company-profile-service
    server:
      port: 8080
      forward-headers-strategy: native
    spring:
      application:
        name: company-profile-service
      content:
        fs:
          filesystem-root: ${FS_ROOT:./data/}
      datasource:
        url: jdbc:postgresql://prox-company-profile-service-db:5432/postgres
        username: postgres
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            jdbc:
              lob:
                non_contextual_creation: true
    springdoc:
      # By default Springdoc will remove schemas which do not have references.
      remove-broken-reference-definitions: false
  {{- end }}
