apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prox-company-profile-service.fullname" . }}
  labels:
    {{- include "prox-company-profile-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
